name: CI -> Deploy to STU-ASSIST.ir website
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
          CI: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.1.0
      - run: npm install --global yarn
      - run: yarn
      - run: yarn build
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./build"
          remote_dir: "./public_html"
          delete: "false"
